<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <OutputType>WinExe</OutputType>
	  <TargetFramework>net8.0-windows</TargetFramework>
	  <Nullable>enable</Nullable>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <UseWPF>true</UseWPF>
	  <ApplicationIcon>PixelCryptLogo.ico</ApplicationIcon>
	  <Version>3.2.0.0</Version>
	  <!-- Версия приложения: Major.Minor.Build.Revision
	  0 — Major (главная). Меняется при кардинальных изменениях, несовместимых с прошлой версией.
      0 — Minor (дополнительная). Меняется при добавлении нового функционала, совместимого со старой версией.
      0 — Build (сборка). Обычно это номер коммита или количество дней с начала проекта.
      0 — Revision (ревизия). Исправление багов в рамках текущей сборки.
      -->
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Updater.exe" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="PixelCryptLogo.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Updater.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FontAwesome5" Version="2.1.11" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.5" />
    <PackageReference Include="WindowsAPICodePack" Version="8.0.15.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BackgroundUpdater">
      <HintPath>..\BackgroundUpdater.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
